MAX_PASSAGE_LEN = 851
MAX_QUESTION_LEN = 60
MAX_ANSWER_LEN = 46

MAX_SHORT_PASSAGE_LEN = 68
MAX_SHORT_QUESTION_LEN = 60
MAX_SHORT_ANSWER_LEN = 46

ROOT_STATS_DIR = './experiment_data'

PAD_IDX = 0
START_TKN = 1
END_TKN = 2

<<<<<<< HEAD
GRADIENT_ACCUMULATE = 1
=======
GRADIENT_ACCUMULATE = 50
>>>>>>> master
